name: Trello workflow

on:
  push:
    paths:
      - 'packages/core/**'
      - '.github/workflows/core.yaml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      # - name: Test
      #   run: |
      #     cd packages/core
      #     yarn test

      # - name: Tsc
      #   run: |
      #     cd packages/core
      #     yarn tsc

      - name: Build
        run: |
          cd packages/core
          yarn build

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: packages/core/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
