name: Lambda

on:
  push:
    paths:
      - 'api/**'
      - .github/workflows/lambda.yaml

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Build and deploy
      - run: |
        cd api
        sam build --use-container
        sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-app --s3-bucket ${{ secrets.AWS_REGION }} --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_REGION }}
