name: Trello workflow

on:
  push:
    paths:
      - '!api/**'
      - '!.github/workflows/lambda.yaml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: |
          yarn test

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Tsc
        run: |
          yarn tsc

      - name: Build
        run: |
          yarn build

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
