name: Trello workflow

on: [push]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Lint
        run: |
          yarn lint

      - name: Tsc
        run: |
          yarn tsc

      - name: Deploy
        run: |
          yarn deploy
