name: Trello workflow

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: yarn install --frozen-lockfile
      - run: yarn tsc
      - run: yarn lint
      - run: yarn deploy
