name: Trello workflow

on: [push]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - run: |
          yarn install --frozen-lockfile
          yarn tsc
          yarn lint
          yarn deploy
